In [4]:
print("hello")

hello


In [5]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
import statsmodels.formula.api as smf
import sympy as sym
from collections import Counter
from patsy import dmatrices
from scipy import linalg, stats
from scipy.integrate import quad
from scipy.optimize import minimize
from sklearn.linear_model import LinearRegression
from statsmodels.stats.proportion import binom_test
from statsmodels.stats.weightstats import CompareMeans, DescrStatsW, ttest_ind
from sympy import *
from sympy. stats import *
from sympy.plotting import plot3d

3.1

In [6]:
v = [2,3,5]; len(v)

3

3.3

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

3.4

In [8]:
np.arange(0, 1.01, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [9]:
#3.5
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [12]:
#3.7
u = np.array([10, 20]); v = np.array([2, 3])
u + v

array([12, 23])

In [13]:
#3.9
u = np.array([10, 20]); v = np.array([2, 3])
u.dot(v)

80

In [14]:
#3.10
v = [2, -1, 3, -2]
[x for x in v if x > 0]

[2, 3]

In [16]:
#3.15
df = pd. DataFrame(
	{	'name': ['A', 'B', 'C'],
		'english': [60, 90, 70],
		'math': [70, 80, 90],
		'gender': ['f', 'm', 'm']
	}
)
df

name  english  math gender
0    A       60    70      f
1    B       90    80      m
2    C       70    90      m

In [18]:
df = pd.DataFrame((
	{'name': 'A', 'english': 60, 'math': 70, 'gender': 'f'},
	{'name': 'B', 'english' : 90, 'math': 80, 'gender': 'm'},
	{'name': 'C', 'english': 70, 'math': 90, 'gender': 'm'}
))
df

name  english  math gender
0    A       60    70      f
1    B       90    80      m
2    C       70    90      m

In [19]:
#3.16
df[['english', 'math']]

english  math
0       60    70
1       90    80
2       70    90

In [21]:
#3.17
# df['english']
df.english

0    60
1    90
2    70
Name: english, dtype: int64

In [25]:
#3.18
m = df.iloc[:, [1,2]].values; m

array([[60, 70],
       [90, 80],
       [70, 90]])

In [27]:
english, math = m.T; english, math

(array([60, 90, 70]), array([70, 80, 90]))